<div class="converter-wrapper">
	<h1>Unit Converter</h1>

	<div class="category-tabs" id="categoryTabs">
		<!-- Category buttons will be dynamically generated by JavaScript -->
	</div>

	<div class="converter-body">
		<div class="converter-side">
			<label for="fromUnit">From</label>
			<select id="fromUnit" class="unit-select"></select>
			<input type="number" id="fromValue" class="value-input" placeholder="Enter value">
		</div>

		<div class="swap-icon">
			<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><polyline points="19 12 12 19 5 12"></polyline></svg>
		</div>

		<div class="converter-side">
			<label for="toUnit">To</label>
			<select id="toUnit" class="unit-select"></select>
			<input type="text" id="toValue" class="value-input" placeholder="Result" readonly>
		</div>
	</div>

	<div id="errorMessage" class="error-message"></div>
</div>
