<div class="wpuc-widget">
    <div class="converter-wrapper">
        <div class="category-tabs" id="categoryTabs">
            <!-- Category buttons will be dynamically generated by JavaScript -->
        </div>

        <div class="converter-body">
            <div class="converter-side">
                <label for="fromUnit"><?php _e( 'From:', 'unit-converter' ) ?></label>
                <select id="fromUnit" class="unit-select"></select>
                <input type="number" id="fromValue" class="value-input" placeholder="<?php _e( 'Enter Value', 'unit-converter' ) ?>">
            </div>

            <div class="swap-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <line x1="12" y1="5" x2="12" y2="19"></line>
                    <polyline points="19 12 12 19 5 12"></polyline>
                </svg>
            </div>

            <div class="converter-side">
                <label for="toUnit"><?php _e( 'To:', 'unit-converter' ) ?></label>
                <select id="toUnit" class="unit-select"></select>
                <input type="text" id="toValue" class="value-input" placeholder="<?php _e( 'Result', 'unit-converter' ) ?>" readonly>
            </div>
        </div>

        <div id="errorMessage" class="error-message"></div>
    </div>
</div>
